name: Publish

on:
  push:
    tags:
      - v*

jobs:
  npm-publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build puppeteer
        run: npm run build
      - name: Publish puppeteer
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN_PUPPETEER}}
        run: |
          npm config set registry 'https://wombat-dressing-room.appspot.com/'
          npm config set '//wombat-dressing-room.appspot.com/:_authToken' '${NPM_TOKEN}'
          echo "Publishing puppeteer"
          npm publish
          # DEPRECATED_RANGE=$(node utils/get_deprecated_version_range.js)
          # echo "Deprecating old puppeteer versions: $DEPRECATED_RANGE"
          # npm deprecate puppeteer@$DEPRECATED_RANGE "Version no longer supported. Upgrade to @latest"
      - name: Publish puppeteer-core
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN_PUPPETEER_CORE}}
        run: |
          utils/prepare_puppeteer_core.js
          npm config set registry 'https://wombat-dressing-room.appspot.com/'
          npm config set '//wombat-dressing-room.appspot.com/:_authToken' '${NPM_TOKEN}'
          npm publish

  deploy-docs:
    name: Deploy documentation
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Generate docs
        run: npm run docs
      - name: Version docs
        working-directory: ./website
        run: |
          npm install
          npm run docusaurus docs:version ${GITHUB_REF#refs/*/v}
      - name: Commit to main
        run: |
          git config --global user.email "55107282+release-please[bot]@users.noreply.github.com"
          git config --global user.name "release-please[bot]"
          git add .
          git commit -m "chore: generate v${GITHUB_REF#refs/*/v} docs"
          git push
